CREATE TABLE IF NOT EXISTS Cart (
  CartID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UserID INT UNIQUE,
  TotalPrice DECIMAL(10, 2) DEFAULT NULL,
  FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);
